// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // 마이그레이션은 direct(non-pooler) 커넥션이 필요함 (Neon pooler는 advisory lock 타임아웃 발생, P1002)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
